server:
  port: 8082

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://auth-db:5432/authdb
    username: postgres
    password: Wire2681
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secret: my-super-secret-key-auth-1234567890

