server:
  port: 8086

spring:
  application:
    name: client-service
  datasource:

    url: jdbc:mysql://client-db:3306/clientdb
    username: root
    password: Wire2681
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect


